# Generated by Django 2.2.4 on 2019-08-22 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0002_auto_20190819_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='dateline_request',
            field=models.DateField(default=datetime.date(2019, 8, 22)),
        ),
    ]
