# Generated by Django 2.2.4 on 2019-08-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0003_auto_20190822_0732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requestClass',
        ),
    ]
