# Generated by Django 2.2.5 on 2019-09-10 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0004_auto_20190822_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='donated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_name', models.CharField(max_length=100)),
                ('donate_address', models.CharField(max_length=50)),
                ('donate_email', models.CharField(max_length=50)),
                ('donate_bloodgroup', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='requestclass',
            name='dateline_request',
            field=models.DateField(default=datetime.date(2019, 9, 10)),
        ),
    ]
