# Generated by Django 2.2.5 on 2019-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbankapp', '0005_auto_20190910_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='donated',
            name='donate_mobile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
